import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SERPER_API_KEY = os.getenv("SERPER_API_KEY")
PERPLEXITY_API_KEY = os.getenv("PERPLEXITY_API_KEY")

# Zoho CRM configuration
ZOHO_CLIENT_ID = os.getenv("ZOHO_CLIENT_ID")
ZOHO_CLIENT_SECRET = os.getenv("ZOHO_CLIENT_SECRET")
ZOHO_REDIRECT_URI = os.getenv("ZOHO_REDIRECT_URI")

# SALESFORCE_CLIENT_ID = os.getenv("SALESFORCE_CLIENT_ID")
# SALESFORCE_CLIENT_SECRET = os.getenv("SALESFORCE_CLIENT_SECRET")
# SALESFORCE_REDIRECT_URI = os.getenv("SALESFORCE_REDIRECT_URI")

# HUBSPOT_CLIENT_ID = os.getenv("HUBSPOT_CLIENT_ID")
# HUBSPOT_CLIENT_SECRET = os.getenv("HUBSPOT_CLIENT_SECRET")
# HUBSPOT_REDIRECT_URI = os.getenv("HUBSPOT_REDIRECT_URI")

# DYNAMICS_CLIENT_ID = os.getenv("DYNAMICS_CLIENT_ID")
# DYNAMICS_CLIENT_SECRET = os.getenv("DYNAMICS_CLIENT_SECRET")
# DYNAMICS_REDIRECT_URI = os.getenv("DYNAMICS_REDIRECT_URI")